### ISSUE TITLE
Support for 360 video

### ISSUE THREAD

**Issue by TheNetStriker** [nextcloud/files_photospheres#10]
There are a lot of javascript libraries that are able play 360 videos. Here are just a few examples:

https://github.com/thiagopnts/clappr-video360
http://www.marzipano.net/
https://github.com/videojs/videojs-vr
https://github.com/yanwsh/videojs-panorama

Are there any plans to add support for 360 video playback?

**Comment by R0Wi** [comment]
Sounds like an interesting idea. Do you know, where we can get some example 360 videos for playing around with this?

**Comment by TheNetStriker** [comment]
Here is e.g. the sample video from the Marzipano demo. (Copied from the html source code)

https://www.marzipano.net/media/video/mercedes-f1-1280x640.mp4

There should be also many other examples that can be downloaded if you search on Google. I myself have a Samsung Gear360 and an Insta360 One X camera to test this.

The question is which library would be best suited for this plugin. I myself only used Pannellum and and the Marzipano Tool and both worked good. Sadly the online Marzipano Tool Wizard only supports photos, but the library itself supports video.

**Comment by R0Wi** [comment]
@TheNetStriker here is what i suggest:

- Add an option to the NC context menu with `Open in 360° Viewer`, which appears only on `.mp4`-files
- When clicking this, a new popup opens with the Marzipano-Viewer (https://www.marzipano.net/)
- We will keep the `photosphere-js`-library for images

Unfortunately we're not able to determine if a `.mp4`-file contains 360°-data (at least i don't know how to), so we cannot integrate a normal click-handler. This information must be given by the user.

Would that meet your requirements?
@SudoHenk any comments on this?

**Comment by TheNetStriker** [comment]
@R0Wi Sound good to me. Maybe there will be some mp4 metadata information in the future to identify spherical videos. I e.g. found this rfc on a google project: https://github.com/google/spatial-media/blob/master/docs/spherical-video-v2-rfc.md

**Comment by R0Wi** [comment]
Thanks for the source, i'm going to do some research on this.

As a first step i would implement a contextmenu solution (in the regular filesview only, so no shares). Would you like to be a voluntary and test this feature if i'm ready?

**Comment by TheNetStriker** [comment]
@R0Wi Yes I would like to help testing this new feature. Please let me know if you have a version that I can test.

**Comment by R0Wi** [comment]
@TheNetStriker i have a first working version at https://github.com/nextcloud/files_photospheres/tree/feature/360videos. Just clone the repo and checkout branch `feature/360videos`. If you're not familiar with git i can provide a tarball if you like :-)

Currently only `mp4`-files are supported via contextmenu (right click) in regular file-view. Please let me know your results.

**Comment by TheNetStriker** [comment]
@R0Wi I just installed the new app. I simply cloned the files_photosperes repository into the apps directory and checked out the feature/360videos branch. But I don't get any additional commands in the context menu on mp4 files. I've also tried if an Apache restart helps, but I still don't get an more commands on mp4 files. Do I have to do anything else to get this to work with the debug branch?

**Comment by R0Wi** [comment]
Well the only thing i could imagine is a browser chaching problem. Depending on your browser you could try to clean the cache or (on chrome) use the developer tools on the network tab and tick "disable cache". Let me know your results :-)

**Comment by TheNetStriker** [comment]
@R0Wi Thanks for the hint. I now also works on the other pc.

**Comment by R0Wi** [comment]
So if i understood you right the viewer is working in the expected manner? If so i would provide this feature in the next release.

**Comment by TheNetStriker** [comment]
@R0Wi Yes, everything seems to work as expected.
