### ISSUE TITLE
`An error occured while trying to read xmp-data: Share not found` in shared subfolders with special characters

### ISSUE THREAD

**Issue by raph-topo** [nextcloud/files_photospheres#114]
Hello,
Considering a public share link, showing up as the home icon.
When trying to open a photosphere in a subfolder which includes a `+`, `&` or `;` in its name, photoshere does not work, saying `An error occured while trying to read xmp-data: Share not found`.
Photospheres in subfolders containing spaces, `-` `'` `!` `(` do work fine.
I only found `+`, `&` or `;` to be concerned for.
This makes me think it is related to HTML (un)escaping.
This only applies to public shares, the same subfolders create no issue when browsing as logged in user.

**Comment by R0Wi** [comment]
Thanks for reporting this. I think you might be right and we're currently missing the proper URL encoding. Will have a closer look at this

**Comment by R0Wi** [comment]
Sould be fixed by https://github.com/nextcloud/files_photospheres/commit/9db769bc63e3a072b562e0a342789c127942ac01. Please update to `v1.26.2`, which will be available soon.

**Comment by raph-topo** [comment]
I do confirm this is fixed, congrats and many thanks!
