### ISSUE TITLE
Not possible to use without the correct metadata (DJI sphere & co)

### ISSUE THREAD

**Issue by Noxmiles** [nextcloud/files_photospheres#115]
The DJI Drone Sphere Shots does not have the metadata required to be automatically opened with this app. So, it's just open it with the normal picture viewer. Also rightclick on a file does not work, since the "view with 360° viewer" option is only available for videos and not for pictures.

I can't edit metadata within Nextcloud (?).

Please add an option, to open any image with this photosphere viewer. Maybe rightclick menu for all pictures.

**Comment by R0Wi** [comment]
Would you be able to test my patch by running 

```bash
curl https://github.com/nextcloud/files_photospheres/commit/eb890beff0ee959179fad3c0595d781d32d38363.patch | patch -p1
```

from within the `apps/files_photospheres` folder? Appreciate your feedback!

![image](https://github.com/nextcloud/files_photospheres/assets/19730957/9f3ced2d-5395-4887-9d09-bfb2e774c202)
