### ISSUE TITLE
Version 1.01 not working

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/files_photospheres#13]
See: https://help.nextcloud.com/t/how-should-the-photosphereviewer-work/54690/2

**Comment by R0Wi** [comment]
Could this be the same problem described in #7?

**Comment by TheNetStriker** [comment]
I've also updated to 1.0.1 and disabled the viewer app, but the photo sphere viewer is still not working. I also found no infos in the log regarding the problem. Any ideas what could cause the problem?

**Comment by R0Wi** [comment]
Did you enable the "Gallery-App"? See #15

**Comment by TheNetStriker** [comment]
Yes the Gallery app is enabled. If I click on a PANO_ image the image is opened in the Gallery app instead of the Panorama app.

**Comment by R0Wi** [comment]
Do you see anything in the devtools console? Are the photosphere scrips loaded properly (see https://github.com/nextcloud/files_photospheres/issues/5#issuecomment-502642566)?

**Comment by TheNetStriker** [comment]
@R0Wi I've just tested this. Both .js files are loaded in the devconsole, but I cannot see the request for xmp data. I've tried with the gallery app only, with the viewer app only and with both apps enabled. What could be the problem?

**Comment by R0Wi** [comment]
Ok seems like the xmp-data-check works just fine. This means that your image has no xmp-data stored in it. Is it possible that you post your image here, so that i can analyze it?

**Comment by TheNetStriker** [comment]
I just found out that the problem only occurs on photos from my older Samsung Gear 360 camera. The photos from the Insta360 camera are working. The Gear 360 also contains XMP data, but I guess they provide different infos than the Insta360. I've uploaded an empty photo from my Gear 360 camera to my dropbox: https://www.dropbox.com/s/yv50li7lwq17tow/360_0412_Stitch_YHC.JPG?dl=0

**Comment by R0Wi** [comment]
Thanks for providing the image. Seems like the xmp-data-block is present but there is information missing, which is obligatory for the viewer. Actually the viewer expects the following GPano-Data inside the xmp-block:

FullPanoWidthPixels
FullPanoHeightPixels
CroppedAreaImageWidthPixels
CroppedAreaImageHeightPixels
CroppedAreaLeftPixels
CroppedAreaTopPixels

If none of these are set, the viewer will not open. I actually didn't test if the viewer can open it but i know, that it would request the image twice if we don't provide xmp-data while initialization.

I'll test this and may do some adaption in code these days. Will keep you up to date :-)

**Comment by Sanookmakmak** [comment]
I have set those XMP-parameters, as well as

* ProjectionType = equirectangular
* UsePanoramaViewer = True

I have installed Nextcloud 16.01, Gallery-App 18.3.0 and PhotoSphereViewer 1.0.2. The "Viewer" App 1.0 is disabled and deleted.

But the PhotoSphereViewer does **not** display the panorama as photosphere. It is not renamed to PANO_xyz.jpg anymore.

Here is an example panorama, 360x180°, which is displayed as photosphere in Google Photos:

![Edfu_Tempel_1 Sphere](https://user-images.githubusercontent.com/24833757/60381230-abfca300-9a51-11e9-9d00-186a30b153ab.jpg)

**Comment by Sanookmakmak** [comment]
BTW: PhotoSphereViewer 1.01 stops sharing folders:

https://help.nextcloud.com/t/how-should-the-photosphereviewer-work/54690/3

**Comment by R0Wi** [comment]
Thanks for the image, i'll test this soon.

The sharing issue is fixed in version 1.0.2 see #14

**Comment by Sanookmakmak** [comment]
> The Gear 360 also contains XMP data, but I guess they provide different infos than the Insta360

Here is a workshop how to add XMP metadata to make a photo to a photosphere @TheNetStriker:

https://www.allerstorfer.at/photosphere-xmp-metadaten-zu-360-panorama-hinzufuegen/

**Comment by R0Wi** [comment]
@Sanookmakmak you're right, the viewer-component itself is able to display your image. I'll make some adaption to make the app compatible with it.

**Comment by WNYmathGuy** [comment]
I'm new here. I just tried to use this app today. I didn't know it was available till a few days ago. I'm in Nextcloud 16.0.1 & Photo Sphere Viewer 1.0.2 and I get no reaction when selecting [view in PhotoSphereViewer] for panorama's, semi-spheres or 360 spheres taken with an Android phone. I tried looking at the logs in realtime all levels in an admin window in one browser while trying to view photo spheres as a user in another browser window and I saw nothing looking like an error for this app.

Anything I can do to toss back useful diagnostics to help this app along?

**Comment by R0Wi** [comment]
Hi @WNYmathGuy, thanks for your feedback. I'm not quite sure what you mean if you say "when selecting [view in PhotoSphereViewer]". Do you mean the context-menu? What happens if you just left-click on the image?

**Comment by WNYmathGuy** [comment]
@R0Wi Here are some screenshots and a sample photosphere file.

![Screenshot from 2019-07-05 16-42-18](https://user-images.githubusercontent.com/28640985/60744584-b385e580-9f44-11e9-829f-2b221019320d.png)

![Screenshot from 2019-07-05 16-42-29](https://user-images.githubusercontent.com/28640985/60744587-b680d600-9f44-11e9-8102-75f8f394845b.png)

![Screenshot from 2019-07-05 16-44-27](https://user-images.githubusercontent.com/28640985/60744594-b97bc680-9f44-11e9-949d-f53d4daafd72.png)

##### No right click menu in the normal viewer.

![Screenshot from 2019-07-05 16-44-40](https://user-images.githubusercontent.com/28640985/60744596-bd0f4d80-9f44-11e9-8f13-572adf5db49b.png)

![2016-03-26](https://user-images.githubusercontent.com/28640985/60744610-cbf60000-9f44-11e9-9778-fda144bb487b.jpg)

**Comment by R0Wi** [comment]
Thanks for the material. I didn't manage to get the little contextmenu where it says "Open in PhotosphereViewer" in my NC instance. How did you get that menu? 

And what happens if you directly click on an image?

**Comment by WNYmathGuy** [comment]
> Thanks for the material. I didn't manage to get the little contextmenu where it says "Open in PhotosphereViewer" in my NC instance. How did you get that menu?
> 
> And what happens if you directly click on an image?

I have no idea why the "..." tool has that "Open in PhotosphereViewer" in there. I think at one time that tool menu was an option for nextcloud via an app, but they built it into the core. That's based on my old person's memory though.

Clicking directly on an image in grid view opens it in the standard viewer as a rectangle raster. Theirs no context menu while it's in the standard viewer. 

Does my photosphere file render for you correctly? It was made with either a Nexus 5 or a Nexus 6p a while ago and stored on Google Drive till I found Nextcloud.

**Comment by R0Wi** [comment]
I loaded it into my NC test instance and it's opend correctly. But i'm using the new version 1.0.3, which was launched just a few minutes ago. Would you try it with this version and give me some feedback?

**Comment by WNYmathGuy** [comment]
Oh, damn! That's good! I like the tools at the bottom camouflaged with transparency. Great speed with the photo movement and load time. That option in the "..." tool is gone. To open the photo was either a single click in the grid view or a select in the details view, then a single click on the thumbnail in the Info panel. I love that I can twirl it forever. I assumed that semispheres taken with the same device would open in your viewer, but they don't. I'm not knowledgable with meta-data in pics so I won't guess why that happens. Here's an example file:

![PANO_20150920_125052](https://user-images.githubusercontent.com/28640985/60748226-a6bfbc80-9f59-11e9-8e2c-a1e6a2e4af62.jpg)

Might be worth a screen message in the center that vanishes after 1.5 seconds "Press Esc to close".

**Comment by R0Wi** [comment]
Nice to hear, so if i get you right things working now on normal photospheres? :-D

I'll investigate in the image you mentioned and give you a feedback, if this could be shown in the viewer, too.

To exit the app you actually have to press the ESC-key, we're planning to have a little cross at the top right edge in the future.

**Comment by WNYmathGuy** [comment]
@R0Wi I just tried viewing images taken with a Vivitar DVR978HD camera. It's basically two 2K fisheye cameras back to back with hardware stitching. They don't render in the viewer, they just open like an ordinary rectangular photo. Here's one:

![20190620_193953_000](https://user-images.githubusercontent.com/28640985/60761736-712fd780-a01c-11e9-84af-2d2de16cb9fe.JPG)

Is your app just supposed to open a full photosphere taken with a non-VR camera? Or is the Vivitar not building the file correctly?

**Comment by WNYmathGuy** [comment]
This could be useless information @R0Wi but on a Ubuntu 18.04 desktop this git project let me view those files properly:
[https://github.com/JeremyHeleine/Photo-Sphere-Viewer](https://github.com/JeremyHeleine/Photo-Sphere-Viewer)

Saw it demo'ed here [https://www.youtube.com/watch?v=jRMLL311Cho](https://www.youtube.com/watch?v=jRMLL311Cho)

![Screenshot from 2019-07-06 19-30-13](https://user-images.githubusercontent.com/28640985/60762044-a3ddce00-a024-11e9-84a7-b032e6299103.png)

**Comment by Sanookmakmak** [comment]
> Or is the Vivitar not building the file correctly?

XMP metadata are missing
* https://developers.google.com/streetview/spherical-metadata
* https://www.facebook.com/notes/eric-cheng/editing-360-photos-injecting-metadata/10156930564975277

**Comment by R0Wi** [comment]
Could be, that the xmp-data (at least a "GPano"-information) is missing.

Well the whole magic here is to decide, whether the image should be opend in PhotosphereViewer or in regular image viewer. Both are jpeg-files and therefore have the same mimetype. So we have to do a serverside check of the file, after clicking on it. In version 1.0.3 this check at least expects a GPano tag in the metadata.

But of course i can adapt the check if it makes sense to open those fisheye-pictures in the PhotosphereViewer. But then i need a clear property, which tells me that the file is a fisheye. So i'll have a look at your images and see, if i can find something :-)

**Comment by R0Wi** [comment]
@WNYmathGuy i was able to get it to work. If you'd like to test it you can clone the branch: https://github.com/nextcloud/files_photospheres/tree/feature-improved-xmp into your "files_photospheres"-appfolder

**Comment by WNYmathGuy** [comment]
> @WNYmathGuy i was able to get it to work. If you'd like to test it you can clone the branch: https://github.com/nextcloud/files_photospheres/tree/feature-improved-xmp into your "files_photospheres"-appfolder

I'm a "ya basic" when it comes to git. Do I just navigate to the folder as the Nextcloud admin and run the `git pull` command?

**Comment by R0Wi** [comment]
I'd suggest you clean the nextcloud/apps/files_photospheres folder. Then navigate into that folder and run
`
git clone https://github.com/nextcloud/files_photospheres.git .
`

**Comment by WNYmathGuy** [comment]
One minor thing went wrong. I emptied the `nextcloud/apps/files_photospheres` folder. I was in the `nextcloud/apps/files_photospheres` folder with a shell prompt when executing `git clone https://github.com/nextcloud/files_photospheres.git` and what I should have done was deleted the `files_photospheres` folder then ran the command from the `nextcloud/apps` folder. What I did was move the files from `nextcloud/apps/files_photospheres/files_photospheres` folder into the `nextcloud/apps/files_photospheres` folder then deleted the `nextcloud/apps/files_photospheres/files_photospheres` folder.

The result was no photo was displayed, but there was a reaction to clicking the photo. This is now the same reaction to clicking on ones that worked before and any photo that was taken with the Vivitar. See image below.
![Screenshot from 2019-07-08 18-29-24](https://user-images.githubusercontent.com/28640985/60846923-04991200-a1af-11e9-876e-68f164e901a0.png)

**Comment by R0Wi** [comment]
Well the images you provided worked in my NC instance. I never had this strange behaviour that just a blank page was shown :-)

Are there any errors on your browsers devtools console?

**Comment by WNYmathGuy** [comment]
@R0Wi you sir are talking to a non-web developer. I'm guessing my way through that request though. Here is a screenshot I think may be useful?

![Screenshot from 2019-07-09 10-31-31](https://user-images.githubusercontent.com/28640985/60901237-99e1e800-a23b-11e9-83b8-1919766f810e.png)

**Comment by WNYmathGuy** [comment]
I upgraded my Nextcloud server and now for some reason the photos load as advertised.

**Comment by R0Wi** [comment]
@WNYmathGuy it's quite hard to guess, what's gone wrong for you but i think if it's working now it should be fine. To which NC Version did you upgrade?

I'll push the changes into the appstore these days :-)

**Comment by crossbuilder** [comment]
Here are two files taken with the same cam (DJI).

This one works:  
http://z99a.camedel.de/s/HwxQPXfRyyLnc9k
This one does not.  
http://z99a.camedel.de/s/sst9jTJQgPLZNFE

I can't see any difference in the tags.
Nextcloud 16.0.3 PhotoSphere 1.0.3

Note: Both links will expire on saturday, so please download if you want to keep the images for testing.

**Comment by R0Wi** [comment]
@crossbuilder i moved this to #23. Thanks for your feedback.

**Comment by WNYmathGuy** [comment]
@R0Wi I upgraded from 16.0.1 to 16.0.3 but I don't think it was the problem because it worked on other devices using the same software prior to the upgrade. Maybe it was a browser cache issue?
