### ISSUE TITLE
convert 360 photo

### ISSUE THREAD

**Issue by sechanbask** [nextcloud/files_photospheres#130]
Is it possible to convert 360 photo with https://github.com/ultramango/gear360pano directy into nextcloud ?

It wil be wonderfull !

**Comment by R0Wi** [comment]
Well this app here only integrates a viewer for Photosphere images into the Nextcloud frontend. I don't think that this is the right place to process files in any way. Maybe you want to checkout https://github.com/nextcloud/workflow_script ?
