### ISSUE TITLE
Compatibility with NC 28

### ISSUE THREAD

**Issue by Moini** [nextcloud/files_photospheres#132]
Hi - it would be nice if this app could be updated to be compatible with Nextcloud 28. 

It's a very useful and cool app, and I don't want to miss it when I upgrade - from other NC app developers, I've heard, though, that updating is difficult because the UI js library has changed. 

Maybe this bug report here could serve to keep track of the update.

**Comment by R0Wi** [comment]
Hi @Moini, glad to hear that you like this app. Unfortunately your NC app developer colleagues were right and NC 28 introduces some breaking changes in the frontend. I'm currently trying to find a solution to integrate the Photosphere Viewer into the new frontend. 

You can track the progress here: https://github.com/nextcloud/files_photospheres/pull/131

Also, for NC29, there's an interesting discussion going on [here](https://github.com/nextcloud/viewer/issues/240) on how to migrate this app into the `viewer` app.

So stay tuned :sunglasses:

**Comment by Moini** [comment]
Cool, thanks! I hadn't seen that there was already an in-progress PR. 
Just to clarify: I'm not an app developer myself, I've only read others' discussions.

(did I understand correctly that there has once been a discussion about merging this app into the official one? That would be nice, from a user POV. There's not too much sense in looking at 'flattened' panorama images (although a switch would maybe be useful in some cases).)

**Comment by Moini** [comment]
Wow, thank you, @R0Wi ! Updating our Nextcloud is coming nearer :)  Ich wünsche allen am Projekt Beteiligten einen guten Rutsch + alles Gute für 2024!
