### ISSUE TITLE
App Breaks Share Links

### ISSUE THREAD

**Issue by Chillstice** [nextcloud/files_photospheres#14]
When a user generates a share link for a file after the v1.0.1 update, anyone that tries going to that link - for any file type - will receive an 'Internal Server Error' landing page. 

The following error will also get logged:
`
Error: Class 'OCA\Files_PhotoSpheres\AppInfo\Util' not found
`

Disabling the app will return normal functionality.

**Comment by R0Wi** [comment]
Thanks for reporting. I can confirm this issue and will have a look at it .

**Comment by R0Wi** [comment]
@Chillstice would you please clone the https://github.com/nextcloud/files_photospheres/tree/bugfix_share_links branch and check, if i fixed the problem there?
