### ISSUE TITLE
Not compatible with NC 28 PHP 8.3

### ISSUE THREAD

**Issue by mooninite** [nextcloud/files_photospheres#141]
Hello,

Are there any plans to make this app compatible with Nextcloud 28 or higher?

**Comment by R0Wi** [comment]
I guess you're referring to Nextcloud 29, right? Since support for NC28 has been added many months ago already. NC29 is currently WIP. The current `master` branch code is compatible with Nextcloud 29, I just didn't have the chance to properly test it, yet.

**Comment by mooninite** [comment]
Sorry, I meant version 28. Not 29.

My Nextcloud is showing version 1.27.0 as the latest version of this app. Unfortunately there isn't a force refresh option on checking for app updates. Is there a problem with the Nextcloud repository or is it my local install?

**Comment by R0Wi** [comment]
Version `1.27.0` is the latest version compatible with NC **27**. If you have a look at the compatibility matrix [here](https://apps.nextcloud.com/apps/files_photospheres), you can see that there is already a newer version `1.28.1`, compatible with NC **28** out there 😄 

Upgrading to NC28 will automatically upgrade all your apps as well to the most up-to-date, compatible version.

**Comment by mooninite** [comment]
I am running NC28. NC28 is showing me 1.27.0.

**Comment by R0Wi** [comment]
That's weird. `1.27.0` shouldn't show up on NC28 since it is only compatible to NC27. Did you try to remove and reinstall the app?

**Comment by mooninite** [comment]
I tried to remove it but the install page says 1.27.0. If I try the "Download and enable" button anyway I get a notification saying "An error occurred during the request. Unable to proceed. App "Photo Sphere Viewer" cannot be installed because it is not compatible with this version of the server."

**Comment by AlBundy00** [comment]
I'm on "Nextcloud Hub 7 (28.0.3)" and cannot run/install the app. I see this:

![Screenshot 2024-05-07 122644](https://github.com/nextcloud/files_photospheres/assets/50870366/e478fe85-6a95-48ef-80f3-4d80ff7d3d68)

Due to notes for version 1.28.1 it should support these php versions:

PHP    >=8.0.0,<8.3.0

Why this message "PHP with a version lower than 8.2 is required." ?

**Comment by AlBundy00** [comment]
My fault. I activated PHP 8.3! I just saw <8.3.0 and NOT <=8.3.0 ;-)
I switched back to PHP 8.2 and now the app is working.

**Comment by R0Wi** [comment]
Ok but it seems to me that @mooninite is facing a different problem which is apparently not related to this app itself but rather the NC app(-store) infrastructure.

As a workaround you can download the latest NC28 compatible artifact from [here](https://github.com/nextcloud/files_photospheres/releases/download/v1.28.1/files_photospheres.tar.gz) and unzip + untar it in your `/app` directory. Alternatively please follow the instructions in our [Readme](https://github.com/nextcloud/files_photospheres?tab=readme-ov-file#install-manually).

**Comment by mooninite** [comment]
My NC 28 install (Fedora) is now showing me version 1.23.1 from the app store.

I manually installed 1.28.1 but since Fedora 40 uses PHP 8.3.0 I cannot use the app.

Thanks for your time.

**Comment by R0Wi** [comment]
I guess you're right. Didn't notice that NC 28 already added support for PHP 8.3 but it's clearly stated in the [docs](https://docs.nextcloud.com/server/28/admin_manual/installation/system_requirements.html). So we will add support for 8.3 as well.

**Comment by R0Wi** [comment]
Fixed in [`v1.28.2`](https://github.com/nextcloud/files_photospheres/releases/tag/v1.28.2)
