### ISSUE TITLE
The "close" button in the upper right corner has no function.

### ISSUE THREAD

**Issue by AlBundy00** [nextcloud/files_photospheres#143]
As the subject says. When I click on the X upper right nothing happens. Only way to leave it close the brower tab.
I'm using Chrome. Also tried with Edge. Same thing.

**Comment by laurensbl** [comment]
Same here. Firefox. Weird thing is that sometimes it does work, mostly directly after opening, It then stops functioning after dragging the view around. But... sometimes even after dragging around it keeps working. Mostly not, however.

**Comment by R0Wi** [comment]
I need to have a closer look into this as soon as time permits. I'm suspecting some problems in the code related to the removal of the viewers iframe. Not sure why this only happens "sometimes" but might be a race condition. Will keep you posted ...

**Comment by AlBundy00** [comment]
Not a big deal.

>>Will keep you posted ... 
Thanks a lot!

**Comment by R0Wi** [comment]
Could you please share which Nextcloud- and App-version you're using?

**Comment by laurensbl** [comment]
Just checked, behavior occurs with Nextcloud 28.0.6 en app version 1.28.1.

**Comment by R0Wi** [comment]
Thanks for the feedback. `v1.28.2` did not yet fix the problem.

Would you be so kind and try the artifact from https://github.com/nextcloud/files_photospheres/actions/runs/9378221736/artifacts/1569478425 ? I applied a fix there which seems to work for me and I would love to hear your feedback.

**Comment by laurensbl** [comment]
Tried the artifact and the button seems to work fine now, Tried with several spheres on different locations (local and on external storage), didn't get it to fail.

**Comment by R0Wi** [comment]
Thanks for the feedback. I incorporated the changes into `v1.28.3` 👍

**Comment by AlBundy00** [comment]
Close button now working.

Thanks a lot for your work!
