### ISSUE TITLE
App does not work without Gallery-App

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/files_photospheres#15]
It seems like deactivating the Gallery-App breaks this app. See #5 for details.

**Comment by R0Wi** [comment]
When deactivating the Gallery-App, the registration of the click-handler
`
OCA.Files.fileActions.registerAction
`
still works, but it doesn't get invoked by the framework anymore.

**Comment by SudoHenk** [comment]
This behaviour is indeed quite strange, as if the Gallery app provides the onclick listener in the file browser.

If you enable "Viewer" or the "Gallery", the registration listener works, if you disable them both it doesn't work.
