### ISSUE TITLE
Can't display sphere when clicking on a thumbnail

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/files_photospheres#2]
The app works great when I open the photo from the file manager or the list view in the gallery. However when I click on the thumbnail in the gallery it opens the normal gallery viewer instead of the photo sphere viewer.
Is this fixable?

(NOTE :: this issue was moved from [https://github.com/R0Wi/Nextcloud-PhotoSphereViewer/issues/2]())

**Comment by SudoHenk** [comment]
I don't think this can be done without modifying the gallery app itself. There are no hooks available in the gallery app (https://github.com/nextcloud/gallery/search?q=dispatch&unscoped_q=dispatch results in no internal event dispatches).

**Comment by R0Wi** [comment]
I think i would be more interesting to focus on the newer "Viewer-App". As far as i know this will replace the "Gallery-App" in the future.
@skjnldsv is there a chance to get such a hook implemented?

**Comment by skjnldsv** [comment]
@R0Wi a hook is already there yes :)
Example on the text app: https://github.com/nextcloud/text/blob/a5cf029eb50bde6fb4b3df7db20dc88ca0912da7/src/files.js#L30

**Comment by skjnldsv** [comment]
Though, we should indeed add some kind of priority or other check (no clue yet) to make sure you can register a second handler on the same mime.
@juliushaertl any idea?

**Comment by R0Wi** [comment]
@skjnldsv thanks for your feedback. At the moment we solved this problem by registering a handler for the mime "image/jpeg". Then we listen for the "registerAction"- event and overwrite the newly added actionhandler (see https://github.com/nextcloud/files_photospheres/blob/master/js/fileAction.js#L217). But we store the "old" action handler so that if we determine the clicked image isn't a photosphere, we call the "old" action handler to view the image.

So one possible solution could be to register more than one actionhandler for the same mimetype (maybe with some kind of priority) and then have a event emmited where the handler can signalize, if he already handled the event (like a "e.handled = true").

**Comment by skjnldsv** [comment]
Well, we could also just detect if the image is a sphere and load a specific view directly on the viewer :wink:
