### ISSUE TITLE
Button for closing the viewer

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/files_photospheres#22]
It would be nice to have a little cross at the top right corner to close the viewer overlay (see gallery app etc).

@SudoHenk would that be a task for you?

**Comment by jelinj8** [comment]
It took me a while to find ESC key for closing the viewer. Not available on touchscreen!

**Comment by SKB-CGN** [comment]
Same here.
The app is great, but closing the viewer with ESC is either not available on mobile devices.
A little "X" somewhere would be great.

**Comment by R0Wi** [comment]
Just to mention: a possible workaround wo be to use the "go back" function of your browser. If you're on Android you can use the back arrow button. Don't know how it looks like on iOS/Safari devices but "going back" should be possible :+1:

**Comment by SKB-CGN** [comment]
> Just to mention: a possible workaround wo be to use the "go back" function of your browser. If you're on Android you can use the back arrow button. Don't know how it looks like on iOS/Safari devices but "going back" should be possible :+1: 

Sure, but currently every popup has an "X" to close. The user is used of it.

**Comment by SKB-CGN** [comment]
Hi, just got an update for the app 1.24.2 but there is still no closing button. As i understand, it should appear in top right corner, right?

**Comment by R0Wi** [comment]
Yes, should be included in `1.24.2`. Just a first guess: could you try to clear your browsers cache, please?

**Comment by SKB-CGN** [comment]
Did it. I found out, that the button is only appearing when entering fullscreen mode and leaving it. After that, the button is visible. I think, it should be visible directly after opening the picture, right?

Picture opened:
![2022-09-28 13_40_40-Posteingang - stephan kreyenborg@intl att com - Outlook](https://user-images.githubusercontent.com/58603329/192770029-cd7b58b3-95a4-4c43-ae84-cbc76ece6577.png)

Entered fullscreen with exiting via ESC:
![2022-09-28 13_40_51-Posteingang - stephan kreyenborg@intl att com - Outlook](https://user-images.githubusercontent.com/58603329/192770117-17e7eb41-6721-4287-bfa6-54e7413848cf.png)

**Comment by R0Wi** [comment]
Yes, you're of course correct. Will try to reproduce this, currently I'm not really sure what the problem could be. 

By "fullscreen mode" you mean the fullscreen mode from the photosphere viewer library at the bottom bar, right? Not the one of your browser?

**Comment by SKB-CGN** [comment]
Yes, i mean the buttons on the below right corner.

![2022-09-28 15_28_50-Posteingang - stephan kreyenborg@intl att com - Outlook](https://user-images.githubusercontent.com/58603329/192791203-198d9b75-cc54-4d76-a49c-bb9965753afc.png)

**Comment by R0Wi** [comment]
Sorry but I cannot reproduce the issue. If I open a panorama image, the button is displayed as expected. When going into fullscreen mode, the button disappears but I think that's kind of "normal"?

**Comment by SKB-CGN** [comment]
Yes, that should be the normal behavior. 

On my side, the button is only visible after entering and exiting the full screen - not directly after opening the 360 deg image.

**Comment by R0Wi** [comment]
Hi @SKB-CGN , I can now reproduce the behaviour you mentioned. Don't know why but this did not happen on my dev machine.

I'll try to find a stable solution. Would you volunteer to test a new version before I release it to the AppStore?

**Comment by SKB-CGN** [comment]
Great.
Sure, just let me know, how I would be able to test it.

Thanks!

**Comment by SKB-CGN** [comment]
Sorry, this took a while.

I have installed the mentioned version. This one is working as expected. The button is displayed directly while loading - so the users is also able to cancel opening the picture while loading.

Thanks!

**Comment by R0Wi** [comment]
Great, thank's for testing
