### ISSUE TITLE
Some Images are not working

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/files_photospheres#23]
Here are two files taken with the same cam (DJI).

This one works:
http://z99a.camedel.de/s/HwxQPXfRyyLnc9k
This one does not.
http://z99a.camedel.de/s/sst9jTJQgPLZNFE

I can't see any difference in the tags.
Nextcloud 16.0.3 PhotoSphere 1.0.3

Note: Both links will expire on saturday, so please download if you want to keep the images for testing.

**Comment by WNYmathGuy** [comment]
I tried the links too and as he said, the first worked, the second didn't. F-ing beautiful photo!

**Comment by R0Wi** [comment]
@crossbuilder i think this will be fixed in version 1.0.4. The images are both working in my NC instance with the app-version 1.0.4 . So i will provide the update as soon as possible.

**Comment by TheNetStriker** [comment]
I think I have the same problem with version 1.0.3. The images from my Samsung Gear 360 camera are now loaded into the panorama viewer, but it only displays a black image. You can test this with the same example image from the other issue: https://www.dropbox.com/s/yv50li7lwq17tow/360_0412_Stitch_YHC.JPG?dl=0

I found the following errors in the Chrome developer console:

```
[Violation] Forced reflow while executing JavaScript took 34ms
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
three.min.js?v=1.0.3:174 THREE.WebGLRenderer 93
three.min.js?v=1.0.3:117 WebGL: INVALID_VALUE: texImage2D: no canvas
texImage2D @ three.min.js?v=1.0.3:117
k @ three.min.js?v=1.0.3:126
(anonymous) @ three.min.js?v=1.0.3:193
bg @ three.min.js?v=1.0.3:46
db.upload @ three.min.js?v=1.0.3:607
n @ three.min.js?v=1.0.3:171
Zd.renderBufferDirect @ three.min.js?v=1.0.3:185
m @ three.min.js?v=1.0.3:158
l @ three.min.js?v=1.0.3:157
Zd.render @ three.min.js?v=1.0.3:192
d._render @ photo-sphere-viewer.min.js?v=1.0.3:7
d._setTexture @ photo-sphere-viewer.min.js?v=1.0.3:7
(anonymous) @ photo-sphere-viewer.min.js?v=1.0.3:7
Promise.then (async)
d.setPanorama @ photo-sphere-viewer.min.js?v=1.0.3:7
d @ photo-sphere-viewer.min.js?v=1.0.3:7
(anonymous) @ init.js?v=1.0.3:45
files_photospheres:1 [.WebGL-000001FB03744EE0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
files_photospheres:1 [.WebGL-000001FB03744EE0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

I will also test this again when version 1.0.4 is released.

**Comment by crossbuilder** [comment]
Works now!  Thanks!

**Comment by TheNetStriker** [comment]
I've just tested this in 1.0.4 but i still get the errors on the Gear360 images. The images from my Insta360 are loading just fine. Can you please take a look at this? The Gear360 images also used to work.

**Comment by crossbuilder** [comment]
Here is a 180° picture that doesn't work:

http://z99a.camedel.de/s/fntHdre6tMcfsrj

IIRC this worked with NC15 and PhotoSphere < 1.0 .. but I could be wrong about that.

**Comment by R0Wi** [comment]
@crossbuilder thanks for the feedback. I'll fix this in the next version. The xmp-data check is quite annoying ;-)
@TheNetStriker is it possible for you to provide the image which is not working

**Comment by R0Wi** [comment]
@TheNetStriker indeed your image is working on an older version of photosphere-viewer.js (tested v.2.9). Unfortunately i have no idea whats wrong because these are internals of the library. So maybe you'd like to write a new issue here https://github.com/mistic100/Photo-Sphere-Viewer/issues ?

**Comment by R0Wi** [comment]
@TheNetStriker i did some research and it seems that your image contains just some parts of the xmp-data. This breaks the component if we don't provide the full data. If we provide no xmp-data (and let the component load the image twice) it works. I'll investigate in that and keep you up to date :-)

**Comment by Sanookmakmak** [comment]
> Here is a 180° picture that doesn't work:

@crossbuilder, that panorama isn't a photosphere because XMP-GPano parameters are missing.

**Comment by R0Wi** [comment]
> @crossbuilder, that panorama isn't a photosphere because XMP-GPano parameters are missing.

Thats correct, the metadata doesn't provide any cropping information. But with version 1.0.5 this image will be shown in panorama-viewer anyway, because it has a 'GPano' string in the xmp-metadata section.

**Comment by R0Wi** [comment]
> I've just tested this in 1.0.4 but i still get the errors on the Gear360 images. The images from my Insta360 are loading just fine. Can you please take a look at this? The Gear360 images also used to work.

@TheNetStriker  Did you test it with version 1.0.5? Should be fixed there.

**Comment by TheNetStriker** [comment]
@R0Wi I've just tested this in 1.0.5 and it works. Thanks for the quick fix!

**Comment by totti4ever** [comment]
I am having problems with cardboard and gear360 (rev1) images, photosphere pics from GCam are working. I made all three available (will expire end of next week):
https://cloud.jacobsen.online/s/vr-issue

**Comment by R0Wi** [comment]
Ok which problems do you have in detail? I visited your link and was able to view all 3 images in the photosphere-viewer by clicking on it..?

**Comment by totti4ever** [comment]
> Ok which problems do you have in detail? I visited your link and was able to view all 3 images in the photosphere-viewer by clicking on it..?

insane - it is working with all of them now, no clue what I did wrong before!
cheers for checking!

**Comment by R0Wi** [comment]
Since there haven't been posts here for a long time i will close this for now
