### ISSUE TITLE
nextcloud 17 compatibility

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_photospheres#28]
hello! a nice neat app! any plans to make it compatible with  nc17?

**Comment by R0Wi** [comment]
Hi,

thanks for your feedback. I'm going to investigate in that these days but at the moment i don't see any problems to make the app compatible with nc17. 

I'll kepp you up to date :-)

**Comment by elpraga** [comment]
I've enabled it as an untested app, and it seems to be working just fine. I assume, it should be easy to bump the version up and get rid of the red warning that could scare off some people.

Thanks for a nice piece of soft!

**Comment by R0Wi** [comment]
Would also surprise me, if there was some breaking changes with NC17 which make the app incompatible. But let me check this quickly, then i'll update the config-file.

**Comment by R0Wi** [comment]
Ok i checked the functionallity and all seems to be fine with NC17. But i encountered a little UI-error, because of the bug i submitted here: https://github.com/nextcloud/server/issues/17515. In detail the viewers vertical space was too big when i tested the app. So it reached down to the end of the page and i had to scroll down to see the controls on the bottom. You can check this if you have a file-view with a view files (about 10 or more), so that the scrollbars are visible clearly.

If this error is fixed the app will be made compatiple with NC17.

**Comment by elpraga** [comment]
Thank you @ROWi I did not encounter any issues when I enabled it on my server.  Will check the error you've reported.

**Comment by Sanookmakmak** [comment]
I've updated to Nextcloud 17.01, i have a white page with the Photo Sphere Viewer v 1.05 instead a panorama :-(

App does not work @R0Wi

**Comment by R0Wi** [comment]
@Sanookmakmak that sounds bad. Do you have some error logs of your browser and maybe you NC instance? For me it worked with NC17 despite the error mentioned in https://github.com/nextcloud/server/issues/17515 (not sure if they will patch back for NC17 or if the error will be fixed in the new NC18 only)

**Comment by Sanookmakmak** [comment]
I found it out - WebGL was disabled ;-)
Now it seems to work.

![webgl_disabled](https://user-images.githubusercontent.com/24833757/69502922-bba2e980-0f14-11ea-8161-6fee90dbc0bc.png)

**Comment by R0Wi** [comment]
> I found it out - WebGL was disabled ;-)
> Now it seems to work.
> 
> ![webgl_disabled](https://user-images.githubusercontent.com/24833757/69502922-bba2e980-0f14-11ea-8161-6fee90dbc0bc.png)

Interessting, didn't know this feature can be disabled in the browser. Could be a little improvement that we show an alert in this case :-)

**Comment by Sanookmakmak** [comment]
The JonDonym IP check is suggesting to turn WebGL off in the browser: http://ip-check.info/?lang=de

**Comment by R0Wi** [comment]
> The JonDonym IP check is suggesting to turn WebGL off in the browser: http://ip-check.info/?lang=de

Well the photosphere-js-library uses three.js lib under the hood which uses WebGL for rendering the photosphere image. So i'm afraid there is nothing we can do here if you decide to turn off WebGL in your browser :-/

**Comment by clidx** [comment]
> > I found it out - WebGL was disabled ;-)
> > Now it seems to work.
> > ![webgl_disabled](https://user-images.githubusercontent.com/24833757/69502922-bba2e980-0f14-11ea-8161-6fee90dbc0bc.png)
> 
> Interessting, didn't know this feature can be disabled in the browser. Could be a little improvement that we show an alert in this case :-)

This just happened to me too. It appears to be disabled in Chrome by default, or at least Chromium on Linux. I thought the entire plugin was just bugged because there was no error message or anything.

**Comment by R0Wi** [comment]
> > Interessting, didn't know this feature can be disabled in the browser. Could be a little improvement that we show an alert in this case :-)
> 
> This just happened to me too. It appears to be disabled in Chrome by default, or at least Chromium on Linux. I thought the entire plugin was just bugged because there was no error message or anything.

Thanks for your feedback. I'm working on an alert so it's clear to the user that he has to enable WebGL support. I'm going to test it with chromium and iceweasel browsers, too. Please refer to https://github.com/nextcloud/files_photospheres/tree/feature-webgl-support-detection branch for more information.

**Comment by R0Wi** [comment]
@clidx i moved this issue [here](https://github.com/nextcloud/files_photospheres/issues/33).

I'm closing this now, because there a no more NC17 related issues. Feel free to reopen, if someone else encounters any problems with NC17.
