### ISSUE TITLE
Establish CI with Travis/Scrutinizer/CodeCov

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/files_photospheres#29]
I would really like to establish a CI pipeline with automatic builds, testing and deployment. Unfortunately i can't add the repository to Travis/Scrutinizer/CodeCov because i'm not the owner. Let's say i would like to setup a similar pipeline like other apps (like https://github.com/nextcloud/files_pdfviewer) do.

@LukasReschke @MorrisJobke is there a way to accomplish this?

**Comment by R0Wi** [comment]
@skjnldsv any help would be appreciated please.

**Comment by skjnldsv** [comment]
Hey :)
Travis is enabled for the whole company, you can just add a travis config file and it will trigger
We're also using our own drone servers, so you might want to consider using drone as well, as it offers more versatility with your tests :)

**Comment by R0Wi** [comment]
Thanks for your feedback. Is travis also enabled on branches so i can test it on a test branch? I'll take a look at drone , too :-)

**Comment by skjnldsv** [comment]
yes, create a pull request and you'll get your github feedback :)

**Comment by R0Wi** [comment]
@skjnldsv thanks for you help. I did a setup for `drone` on #42 but it doesn't run automatically. The config from https://drone.nextcloud.com/nextcloud/files_photospheres/settings says "activate repository" but if i click the button i get "There was a problem enabling your repository. Not Found.". Am i missing something here?

**Comment by skjnldsv** [comment]
Hey !
In the meantime we tried to move away from drone as much as we can, because it takes forver now :(
We have too much tests running on our servers ^^
You can see your github actions examples in the app-tutorial repostory though, this is blazing fast and awesomely simple! :D

https://github.com/nextcloud/app-tutorial/tree/master/.github/workflows

**Comment by skjnldsv** [comment]
> i click the button i get "There was a problem enabling your repository. Not Found.". Am i missing something here?

I guess you need the permissions to do so :see_no_evil: Let me activate for you!

**Comment by R0Wi** [comment]
Thanks for your great support :-) I'll have a look at the github actions. By the way: is it possible to add me as "administrator" for this repository? Because i can't configure any merge-checks etc. which is quite annoying :-/

**Comment by skjnldsv** [comment]
Done, sorry about that, good enough?

**Comment by R0Wi** [comment]
Perfect, thanks so much for your support :-D

**Comment by skjnldsv** [comment]
You're very welcome! :hugs:

**Comment by R0Wi** [comment]
@skjnldsv may i just annoy you one last time:
i did a setup with GitHub Actions (very nice by the way, thanks) and i would like store some secrets (app key) in the `Secret` tab of the repo-settings for automatic signing and deployment. Unfortunately i do only have the rights to see tabs `Options` and `Interaction limits`. Is it possible to activate the tabs `Secrets`, `Branches` and `Webhooks`, too please?

**Comment by skjnldsv** [comment]
You're not annoying me :)
Should be good now?

**Comment by R0Wi** [comment]
Perfect, thanks a lot :-)
