### ISSUE TITLE
incompatible with external authentication

### ISSUE THREAD

**Issue by jmptbl** [nextcloud/files_photospheres#32]
There seems to be a compatibility issue between the files_photospheres and user_external plugins:

https://github.com/nextcloud/user_external

My Nextcloud instance uses external IMAP authentication. While logged into Nextcloud if I try to open a photosphere, it looks like the photoviewer tries to start (`/apps/files/?dir=/Photos/Camera-Pixel&fileid=472#photo-sphere-viewer-frame` in the URL), but it causes the browser to popup an authentication dialog. Even if I re-enter my login details correctly, the next screen is just a blank page with message "Cannot load image" in the top left.

However, if I share a photosphere publicly, and load that share link, photosphere loads up fine and displays the photo. BTW it looks great when it works!!!

Any chance you could look at compatibility with the user_external plugin, please?

**Comment by R0Wi** [comment]
Thanks for your feedback. At the moment i can't say whats causing this issue but i'll investigate further by setting up the external auth app on my dev machine. I will keep you up to date.

**Comment by R0Wi** [comment]
@jmptbl in the meantime you could provide some more information if possible, please. So there are two things which could help:
1. the network tab log of your browser (would be good to see all the requests going on so make sure the "keep history" checkbox is active
2. your NC config snippet, which is responsible for configuring the external authentication app.

**Comment by R0Wi** [comment]
@jmptbl i did a quick setup with the `user_external` app combined with a samba authentication (because i don't have a IMAP server ready). Unfortunately i can't reproduce the error you mentioned, everything is working like expected. 

Your comment
> My Nextcloud instance uses external IMAP authentication. While logged into Nextcloud if I try to open a photosphere, it looks like the photoviewer tries to start (`/apps/files/?dir=/Photos/Camera-Pixel&fileid=472#photo-sphere-viewer-frame` in the URL), but it causes the browser to popup an authentication dialog. 

by the way sounds like there is some kind of Basic Authentication going on. Could this be due to some special kind of server configuration?

**Comment by jmptbl** [comment]
I believe I have found the issue. The cause is actually not external authentication, rather the definition of d.DEFAULTS.with_credentials in photo-sphere-viewer.min.js.

It is set to !1 (false), and that config parameter gets used to determine the CrossOrigin parameter on the image loader. When false, CrossOrigin is set to anonymous, which according to [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin) instructs the browser to exclude cookies and authentication headers from the resulting request.

Without any cookies, the session is unknown to Nextcloud, which causes it to return 401 to make the browser prompt the user and use HTTP authentication for the request.

I use Safari, and I think this problem might be triggered in Safari only. I tested with Chrome and it doesn't happen, so I assume Chrome ignores the CrossOrigin attribute. In my photo-sphere-viewer.min.js I've set d.DEFAULTS.with_credentials to !0 which resolves the problem in Safari, with no adverse effect to Chrome.

Do you think with_credentials should default to false? It doesn't seem correct to me, but not sure. Thank you for responding so quickly!

**Comment by R0Wi** [comment]
Thanks for this analysis. The setting you mentioned can be overwritten when creating the viewer component so no need to manipulate the default value.

If i get things right the setting is applied mainly at two places:
1. when loading the image within the three.js library (https://github.com/mistic100/Photo-Sphere-Viewer/blob/9bf664a2239081aad2d85cbb060b4e34424e7857/src/js/services/PSVTextureLoader.js#L109)
2. when loading the xmp metadata of the image (https://github.com/mistic100/Photo-Sphere-Viewer/blob/9bf664a2239081aad2d85cbb060b4e34424e7857/src/js/services/PSVTextureLoader.js#L352). We'll in our case this is done before actually calling the component (https://github.com/nextcloud/files_photospheres/blob/c6fd3ee1526332ca8de9c85782e8c661c5089c4b/js/fileAction.js#L206) so this code won't be reached.

But nevertheless the link you posted and this link here (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) both talking about cross origin requests. When opening a photosphere a new iframe will be created, pointing to the domain of your NC instance (https://github.com/nextcloud/files_photospheres/blob/c6fd3ee1526332ca8de9c85782e8c661c5089c4b/js/fileAction.js#L138) so i don't see any cross origin request? Is it possible that you share the browser network of your safari in both cases (with and without the discussed setting)?

**Comment by R0Wi** [comment]
I have some news on this: seems that this is a general issue in Safari and doesn't directly correspond to the `external authentication` app. I was able to reproduce the issue by simply logging in to my NC instance (on a Mac Safari) and opening a photosphere image. The browser tab shows, that the session cookie is not set in the request for the image. This request is send inside of the iframe which should show the image afterwards. So NC reacts by requesting a basic authorization and that's why you observed a popup with username and password.


<img width="960" alt="Bildschirmfoto 2019-12-24 um 17 22 33" src="https://user-images.githubusercontent.com/19730957/71420088-843e6e80-2673-11ea-8314-3c25e53fdf03.png">
In this screenshot you can see, that the session cookie is missing in the request-section ("Anfrage").

**Comment by jmptbl** [comment]
@R0Wi Sorry I didn't manage to provide the detailed analysis you needed. I was having issues capturing Safari's development inspector, and had shift focus to other work. Thank you for pursuing it on your own and merging a fix!  Much appreciated.
