### ISSUE TITLE
Lacking support for upcoming NC18

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_photospheres#35]
Please, make the app compatible with NC18!

It's a great and useful app!

**Comment by R0Wi** [comment]
Please checkout https://github.com/nextcloud/files_photospheres/releases/download/1.0.7-beta1/files_photospheres.tar.gz and let me know your results. I successfully tested this version under NC18 alpha, by extracting it directly into the `NEXTCLOUD_ROOT/apps`-folder and giving file-permissions to the webserver-user (e.g. `chown -R www-data:www-data NEXTCLOUD_ROOT/apps/files_photospheres`).

Thanks for sharing your results :-)

**Comment by elpraga** [comment]
Thank you @R0Wi for your reply. There are still some critical apps I'm waiting to be updated before upgrading my NC to NC18.

I'll test it once I do the upgrade, and I'll let you know.

**Comment by elpraga** [comment]
The version 1.0.7 seems to be working fine with NC18. Controls do not appear on my phone in portrait mode, they do appear on my tablet in porttrait mode though.

Thank you!

**Comment by R0Wi** [comment]
Ok i'll close this for now. Please add a new issue for the problems with the controls and add some further information about the phone and the browser you're using. Thanks for your feedback :-)
