### ISSUE TITLE
photo does not open

### ISSUE THREAD

**Issue by tomash12** [nextcloud/files_photospheres#39]
when I want to open a photo a message pops up "No app is registered to show regular non-photosphere images"
http://serwer.kaldron.pl/index.php/s/Cdekt55p5q358JP
help :)

**Comment by R0Wi** [comment]
Do you have an app registered for viewing regular images like the gallery-app or the viewer-app? The image you provided isn't a photosphere so the app for regular jpeg's is triggerd and this message only shows up if there isn't such.

**Comment by tomash12** [comment]
when I am logged in, I can only open it when I send a link I cannot,

how to install gallery-app. - I do not see the application 
![Przechwytywanie](https://user-images.githubusercontent.com/63071390/78295523-90688080-752c-11ea-885b-176db6b80da6.JPG)

**Comment by R0Wi** [comment]
Ok i see you've installed the viewer app thats fine. Gallery is deprecated. Let me analyze that, i'll keep you up to date.

**Comment by R0Wi** [comment]
@tomash12 is did a little debugging and i noted that the `viewer` app doesn't popup on link shares at all (not on directory-share neither on single-file-share). So this could be an issue or a missing feature. If you like please open a new issue on their site: https://github.com/nextcloud/viewer

If i disable the `Photosphere Viewer`-App, the file just download after clicking on it. So there you are right, that the app changes the default-behaviour of NC and thats a bug. I'll fix this with the next version.
