### ISSUE TITLE
Don't break Fotos App of NC 18.0.4

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/files_photospheres#47]
With Photo Sphere Viewer 1.0.8 installed the official Fotos App does not work anymore: [https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/68?u=sanook)

**Comment by R0Wi** [comment]
Hi @Sanookmakmak, just to be sure: are you talking about sharing a single file or are you sharing a complete folder via public link?

**Comment by R0Wi** [comment]
> Hi @Sanookmakmak, just to be sure: are you talking about sharing a single file or are you sharing a complete folder via public link?

Found the culprit. Will be fixed in 1.0.9.

**Comment by R0Wi** [comment]
Note that you'll have to update to at least NC 18.0.4 to have the corresponding viewer-app fix with https://github.com/nextcloud/viewer/commit/19cf4cba91a3b893b81efac71c9b1d6e4ba5b18e
