### ISSUE TITLE
Nextcloud 19 support

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_photospheres#50]
Could you, please, update this great so to work with Nextcloud 19?

**Comment by R0Wi** [comment]
Will work on this today

**Comment by elpraga** [comment]
Thank you, that's great news!!

**Comment by R0Wi** [comment]
Created the new release and uploaded it to NC appstore. Should be available soon. I did a quick test and everything seems fine but feel free to reopen if you encounter any troubles with NC 19.
