### ISSUE TITLE
Add support for shared photospheres

### ISSUE THREAD

**Issue by SudoHenk** [nextcloud/files_photospheres#6]
Instead of showing the plain image, we should use the photosphere viewer on images that were shared and are in fact a panorama.

I've been fiddling around with this last week, but wasn't really satisifed with the end result. It is possible to make the endpoint public, and pass the sharing token to request the image. However, nextcloud will display the header as if you were just logged in (with files, galary etc.).

Maybe it's an idea, of instead redirecting the client to another URL, just to render the photosphere viewer in an iframe and inject that into the current page?

The files_pdfviewer works the same way.

**Comment by avanc** [comment]
This feature would be great.

**Comment by SudoHenk** [comment]
This is in the release now.
