### ISSUE TITLE
File browser windows empty for copy/move in file but not elsewhere

### ISSUE THREAD

**Issue by Lau-Co** [nextcloud/files_photospheres#67]
Hi,
I met a stange problem with my nextcloud.
I'm not sure this create the problem, but before, I setup group folder, and create group folders with the same name some sharing folder already have.
So I was having a public folder and create a public group folder.
After that, in file, group folder apear with their setting name and sharing folder appear 'renamed' public-2 by the system.

Somewhere after that, here is my filde browser window
![1](https://user-images.githubusercontent.com/52740627/99941548-7bb45380-2d6e-11eb-8324-927d114f42b0.jpg)

But, as mentioned before, in other place (not in file app), here is my file browser window
![1](https://user-images.githubusercontent.com/52740627/99941686-bae2a480-2d6e-11eb-8795-9ebcf41f248e.jpg)

I try to delete all files and folder, use occ command maintenance, repair, file 
nothing change

The only think I see is the ajax spinner not appear for the browser window in file, and appear before dispalying folders/files in the view.
And got an error in console 
Uncaught TypeError: Cannot read property 'contentWindow' of undefined
  at listener.js?v=a3cbea2a-39:82

Nothing in nextcloud.log

Can you help me repair the file browser ?
I'm lose, not understand why same object not working on file app but in Deck or everywhere else.

Tanks,
LauCo

**Comment by Lau-Co** [comment]
Note
 I remove group sharing to
empty cache
try other browsers and other compuetrs

**Comment by R0Wi** [comment]
Hi @Lau-Co, i'm not sure if this is the right place for your problem since this is the `files_photospheres` app which only introduces a viewer for Google photosphere images in the frontend of Nextcloud. Did you pass your issue to the guys at [Nextcloud server](https://github.com/nextcloud/server) ?

**Comment by Lau-Co** [comment]
sorry
i'm newbe

I'm going to ask following your link
thanks
LauCo
