### ISSUE TITLE
Enabling Photos Spere Viewer causes PDF Viewer and Photo Preview shift upwards and leave a blank space at the bottom of the page

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_photospheres#68]
Expected behaviour:
![Screenshot from 2021-01-04 22-30-40](https://user-images.githubusercontent.com/13814570/103581595-9be24100-4edc-11eb-86e7-cc1dee7c2fb2.png)

**Comment by elpraga** [comment]
View when Photo Sphere Viewer enabled: 
![Screenshot from 2021-01-04 22-33-21](https://user-images.githubusercontent.com/13814570/103581920-2d51b300-4edd-11eb-99ff-b297addfd6ce.png)

**Comment by R0Wi** [comment]
Sorry i can't see a real difference? Could you provide a sample pdf, please? And could you also send a list of enabled apps?

**Comment by elpraga** [comment]
Notice the extra space on the bottom. Gimme a sec. I'll switch to white background...

**Comment by elpraga** [comment]
Can you see the white strip at the bottom?

![Screenshot from 2021-01-04 22-41-45](https://user-images.githubusercontent.com/13814570/103582422-1cee0800-4ede-11eb-9ae9-9694882f3d49.png)

**Comment by elpraga** [comment]
The part with **Settings** is part of the page underneath. It also messes up the position of the close button of the PDF Viewer.

**Comment by R0Wi** [comment]
Ah okay now i can see it :-) Ok that's strange i'll dig into this...

**Comment by elpraga** [comment]
I've actually made a previous bug report concerning the PDF Viewer https://github.com/nextcloud/files_pdfviewer/issues/269 before @juliusbr set me on the right track

**Comment by elpraga** [comment]
Thank you @R0Wi !!

Happy New Year!

**Comment by R0Wi** [comment]
Happy new year :-D

Would you like to try the following patch `curl https://github.com/nextcloud/files_photospheres/commit/e2466385889409cde17ad3edc15bf252932516de.patch | patch -p1` from https://github.com/nextcloud/files_photospheres/commit/e2466385889409cde17ad3edc15bf252932516de?

**Comment by elpraga** [comment]
I have tried to apply the patch, but the issue **was not fixed** by the patch. It still continues.

**Comment by R0Wi** [comment]
Could you please clear your browser cache?

**Comment by elpraga** [comment]
I've just did. After clearing the cache, the patch **does fix** the issue!

Thank you for the quick fix @R0Wi !

**Comment by R0Wi** [comment]
You're welcome. Will be fixed with `v1.20.1`.
