### ISSUE TITLE
Not compatible with Nextcloud 16

### ISSUE THREAD

**Issue by Ludovicis** [nextcloud/files_photospheres#7]

**Comment by SudoHenk** [comment]
@Ludovicis fixed just now.

**Comment by Ludovicis** [comment]
Thanks SudoHenk but with the files_photospheres 0.0.3 and Nextcloud 16.0.0; 
the application is not displayed in the menu and when I click on a PANO file ... it's just the viewer of nextcloud that appears. Not the 360 degree pictures.

**Comment by TheNetStriker** [comment]
I have the same problem with Nextcloud 16.

**Comment by R0Wi** [comment]
Ok, it seems like it has something to do with the new "Viewer-App", which was introduced in NC16. If i disable this app, it's working again. So as a workaround for the moment you could do the same, i'll keep you up-to-date.

**Comment by Nebucatnetzer** [comment]
> Ok, it seems like it has something to do with the new "Viewer-App", which was introduced in NC16. If i disable this app, it's working again. So as a workaround for the moment you could do the same, i'll keep you up-to-date.

I can confirm this on the official docker setup.

**Comment by R0Wi** [comment]
@Ludovicis , @TheNetStriker , @Nebucatnetzer would you like to test the compatibility with the viewer-app now? Its acually on branch feature-viewer-integration

**Comment by Nebucatnetzer** [comment]
It's working on my system.

**Comment by Ludovicis** [comment]
Hi R0Wi, it's work also, thanks. 
But the loading time of the image is longer than previous versions. And this is now fully displayed on the page and we no longer have access to the icons (Menu) of nextcloud.

**Comment by R0Wi** [comment]
Thank's for you feedback.

@Ludovicis could you check your devtools network tab and see, which request(s) are long runninig? Does this behaviour only take place on shared view or also on "normal" user view?

**Comment by Ludovicis** [comment]
When I click on a 360 image, i have 127 requests and 6.3Mb transfer. Too difficult to see which longer queries are... Sorry
When i do manually without nextcloud "https://my.nextcloud.com/apps/files_photospheres?url=%2Fremote.php%2Fwebdav%2F%2FPANO_demo9_full.jpg&filename=PANO_demo9_full.jpg&full_width=7680&full_height=3840&cropped_width=7680&cropped_height=3288&cropped_x=0&cropped_y=0", 
it is faster

**Comment by R0Wi** [comment]
Could you sort the requests by size and see, if your image may be loaded twice? Whats the size of your image on its own?

**Comment by Ludovicis** [comment]
The size of my image is 1.8MB, you can find image here https://blog.ipsofactory.it/photosphere-lo-sguardo-app/
I thin than my image ist not loaded twice.

**Comment by R0Wi** [comment]
Sounds strange to my ears. If you have the image with 1.8MB and the total payload of the site is above 6 MB there's something going on ;-)
Whats the payload sum if you directly navigate to the image via the link you provided to us?

**Comment by SudoHenk** [comment]
I've just commited a fix for compatibility with the "Viewer" app. It had to do with the way it registers it handler (uppercase/lowercase with compared to the gallery app).

**Comment by R0Wi** [comment]
Where did you commit the changes? Because i already fixed the compatibility problem with viewer in 
bb50774

**Comment by SudoHenk** [comment]
Ah, you're working in a feature branch! I've pushed my fix alongside some README changes into master. The fix seem to be roughly the same? I guess merging won't be a problem as you can just accept your fix as the head.

**Comment by R0Wi** [comment]
@Ludovicis there has been a problem in the sharing view: the pano images got loaded twice. This should be fixed now, hopefully the app is now running faster while loading the image?

**Comment by Ludovicis** [comment]
Hello R0Wi, the last version the 1.0.4 is very good. The app is now running faster loading the image. No more problem.

Thanks you very much !

**Comment by R0Wi** [comment]
Nice to hear, thank you :-) Had some troubles with uploading the new release because the appstore was down but this morning it worked ;-)
