### ISSUE TITLE
360 Video?

### ISSUE THREAD

**Issue by AlviseNicoletti** [nextcloud/files_photospheres#78]
Do someone know of a "360 Video streaming" version?

Can someone help me / address me to the right thread?

**Comment by R0Wi** [comment]
Hi, you could download a sample 360° video from http://www.marzipano.net/media/video/mercedes-f1-720x360.mp4 for example and store it in your NC instance. Then right click on the file (or use the three point menu button) and choose "View in 360° viewer". You can find additional information in the `README.md`. Does this answer your question?

**Comment by AlviseNicoletti** [comment]
Thank you so much,
I didn't see this !!

**Comment by R0Wi** [comment]
You're welcome 😄 Unfortunately the context-menu solution is currently the only way to explicitly open a `.mp4` file in the 360° viewer because otherwise the app will have to decide if the video is a "normal" video or a 360° one. Didn't manage to distinct this on files metadata, yet 😢
