### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [nextcloud/files_photospheres#81]
Please add compatibility with Nextcloud V23

**Comment by R0Wi** [comment]
Will work on that ASAP 👍

**Comment by leonardohlee** [comment]
Thank you!!

**Comment by R0Wi** [comment]
@leonardohlee a first beta version is available at https://github.com/nextcloud/files_photospheres/suites/4529135046/artifacts/121253753 . Could you imagine to test if everything works for you on your NC23 instance?

**Comment by R0Wi** [comment]
:heavy_check_mark: Tested locally with NC23 
:heavy_check_mark:  Released at https://github.com/nextcloud/files_photospheres/releases/tag/v1.23.0. Also published in NC appstore https://apps.nextcloud.com/apps/files_photospheres.
:warning: Please let me know if you encounter any issues. Thanks to all!

**Comment by leonardohlee** [comment]
Awesome !!
