### ISSUE TITLE
Make the app compatible with NC24

### ISSUE THREAD

**Issue by elpraga** [nextcloud/files_photospheres#87]
Please, make the app compatible with NC24.00.

**Comment by R0Wi** [comment]
I'm working on this already 👍

**Comment by R0Wi** [comment]
Merged and published to appstore. Looking forward to get your feedback :sunglasses:

**Comment by elpraga** [comment]
I've just updated to NC24 and can confirm that the app works as expected. Thank you, @R0Wi !
